// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOY2hyZQu_Ufe-OboqTjKvjTRCxgUBmj4',
    appId: '1:159451731176:web:9bb23b81a0b519871fa55d',
    messagingSenderId: '159451731176',
    projectId: 'fir-modul6-acc71',
    authDomain: 'fir-modul6-acc71.firebaseapp.com',
    storageBucket: 'fir-modul6-acc71.firebasestorage.app',
    measurementId: 'G-PVEHXPX9VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC33R8xKa6X2wcJJX8vkclkjPyWC83R9U',
    appId: '1:159451731176:android:bbec0f4cdf5e14ab1fa55d',
    messagingSenderId: '159451731176',
    projectId: 'fir-modul6-acc71',
    storageBucket: 'fir-modul6-acc71.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOY2hyZQu_Ufe-OboqTjKvjTRCxgUBmj4',
    appId: '1:159451731176:web:a3199bdfe519cb4b1fa55d',
    messagingSenderId: '159451731176',
    projectId: 'fir-modul6-acc71',
    authDomain: 'fir-modul6-acc71.firebaseapp.com',
    storageBucket: 'fir-modul6-acc71.firebasestorage.app',
    measurementId: 'G-64RJR4L6NS',
  );
}
